#!/bin/bash
# MyApp
#
# description: App for PS Quick IT IOT

case $1 in
    start)
        /bin/bash /usr/local/bin/psq-iot-start.sh
    ;;
    stop)
        /bin/bash /usr/local/bin/psq-iot-stop.sh
    ;;
    restart)
        /bin/bash /usr/local/bin/psq-iot-stop.sh
        /bin/bash /usr/local/bin/psq-iot-start.sh
    ;;
esac
exit 0
